"""Curated technical skills for normalization and extraction."""

SKILLS_VOCABULARY: frozenset[str] = frozenset(
    {
        "Python",
        "Java",
        "JavaScript",
        "TypeScript",
        "SQL",
        "PostgreSQL",
        "MySQL",
        "MongoDB",
        "Redis",
        "React",
        "Next.js",
        "Vue",
        "Angular",
        "Node.js",
        "FastAPI",
        "Django",
        "Flask",
        "Spring",
        "Docker",
        "Kubernetes",
        "AWS",
        "Azure",
        "GCP",
        "Git",
        "CI/CD",
        "Linux",
        "REST",
        "GraphQL",
        "Machine Learning",
        "Deep Learning",
        "TensorFlow",
        "PyTorch",
        "Pandas",
        "NumPy",
        "Scikit-learn",
        "NLP",
        "Spark",
        "Hadoop",
        "Kafka",
        "RabbitMQ",
        "Microservices",
        "Agile",
        "Scrum",
        "HTML",
        "CSS",
        "Tailwind",
        "C++",
        "C#",
        ".NET",
        "Go",
        "Rust",
        "Ruby",
        "PHP",
        "Laravel",
        "Terraform",
        "Ansible",
        "Jenkins",
        "GitHub Actions",
        "Tableau",
        "Power BI",
        "Excel",
        "Figma",
        "Jira",
        "Confluence",
        "Salesforce",
        "SAP",
        "Oracle",
        "ETL",
        "Data Engineering",
        "DevOps",
        "SRE",
        "Security",
        "OAuth",
        "JWT",
        "Elasticsearch",
        "Snowflake",
        "dbt",
        "Airflow",
    },
)

_CANONICAL_BY_LOWER = {skill.lower(): skill for skill in SKILLS_VOCABULARY}
