JOB_STATUS_DRAFT = "draft"
JOB_STATUS_PUBLISHED = "published"
JOB_STATUS_CLOSED = "closed"

JOB_STATUSES = (JOB_STATUS_DRAFT, JOB_STATUS_PUBLISHED, JOB_STATUS_CLOSED)

APPLICATION_APPLIED = "applied"
APPLICATION_SCREENING = "screening"
APPLICATION_SHORTLISTED = "shortlisted"
APPLICATION_INTERVIEW_SCHEDULED = "interview_scheduled"
APPLICATION_INTERVIEWED = "interviewed"
APPLICATION_OFFERED = "offered"
APPLICATION_REJECTED = "rejected"
APPLICATION_WITHDRAWN = "withdrawn"

TERMINAL_APPLICATION_STATUSES = frozenset(
    {APPLICATION_REJECTED, APPLICATION_WITHDRAWN},
)

APPLICATION_STATUS_ORDER = [
    APPLICATION_APPLIED,
    APPLICATION_SCREENING,
    APPLICATION_SHORTLISTED,
    APPLICATION_INTERVIEW_SCHEDULED,
    APPLICATION_INTERVIEWED,
    APPLICATION_OFFERED,
]

ALLOWED_APPLICATION_TRANSITIONS: dict[str, frozenset[str]] = {
    APPLICATION_APPLIED: frozenset(
        {APPLICATION_SCREENING, APPLICATION_REJECTED, APPLICATION_WITHDRAWN},
    ),
    APPLICATION_SCREENING: frozenset(
        {
            APPLICATION_SHORTLISTED,
            APPLICATION_REJECTED,
            APPLICATION_WITHDRAWN,
        },
    ),
    APPLICATION_SHORTLISTED: frozenset(
        {
            APPLICATION_INTERVIEW_SCHEDULED,
            APPLICATION_REJECTED,
            APPLICATION_WITHDRAWN,
        },
    ),
    APPLICATION_INTERVIEW_SCHEDULED: frozenset(
        {
            APPLICATION_INTERVIEWED,
            APPLICATION_REJECTED,
            APPLICATION_WITHDRAWN,
        },
    ),
    APPLICATION_INTERVIEWED: frozenset(
        {APPLICATION_OFFERED, APPLICATION_REJECTED, APPLICATION_WITHDRAWN},
    ),
    APPLICATION_OFFERED: frozenset(
        {APPLICATION_REJECTED, APPLICATION_WITHDRAWN},
    ),
}

INTERVIEW_SCHEDULED = "scheduled"
INTERVIEW_COMPLETED = "completed"
INTERVIEW_CANCELLED = "cancelled"
INTERVIEW_NO_SHOW = "no_show"
